apiVersion: v1
data:
  exporterImage: ghcr.io/hyperspike/valkey-sidecar:v0.0.51
  nodes: "3"
  valkeyImage: ghcr.io/hyperspike/valkey:8.0.2
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: valkey-operator
    control-plane: controller-manager
  name: valkey-operator-config
